export type GeoCitySeed = {
  code: string;
  nameFa: string;
  nameEn: string;
};

export type GeoProvinceSeed = {
  code: string;
  nameFa: string;
  nameEn: string;
  cities: GeoCitySeed[];
};

export type GeoCountrySeed = {
  iso2: string;
  iso3: string;
  phoneCode: string;
  nameFa: string;
  nameEn: string;
  sortOrder: number;
  provinces: GeoProvinceSeed[];
};

export const geoSeed: GeoCountrySeed[] = [
  {
    iso2: "IR",
    iso3: "IRN",
    phoneCode: "+98",
    nameFa: "ایران",
    nameEn: "Iran",
    sortOrder: 1,
    provinces: [
      {
        code: "EAZ",
        nameFa: "آذربایجان شرقی",
        nameEn: "East Azerbaijan",
        cities: [
          { code: "tabriz", nameFa: "تبریز", nameEn: "Tabriz" },
          { code: "maragheh", nameFa: "مراغه", nameEn: "Maragheh" },
          { code: "marand", nameFa: "مرند", nameEn: "Marand" },
          { code: "mianeh", nameFa: "میانه", nameEn: "Mianeh" },
          { code: "ahar", nameFa: "اهر", nameEn: "Ahar" },
          { code: "bonab", nameFa: "بناب", nameEn: "Bonab" },
          { code: "sarab", nameFa: "سراب", nameEn: "Sarab" },
          { code: "shabestar", nameFa: "شبستر", nameEn: "Shabestar" },
          { code: "jolfa", nameFa: "جلفا", nameEn: "Jolfa" },
          { code: "ajabshir", nameFa: "عجب‌شیر", nameEn: "Ajab Shir" },
        ],
      },
      {
        code: "WAZ",
        nameFa: "آذربایجان غربی",
        nameEn: "West Azerbaijan",
        cities: [
          { code: "urmia", nameFa: "ارومیه", nameEn: "Urmia" },
          { code: "khoy", nameFa: "خوی", nameEn: "Khoy" },
          { code: "mahabad", nameFa: "مهاباد", nameEn: "Mahabad" },
          { code: "miandoab", nameFa: "میاندوآب", nameEn: "Miandoab" },
          { code: "bukan", nameFa: "بوکان", nameEn: "Bukan" },
          { code: "salmas", nameFa: "سلماس", nameEn: "Salmas" },
          { code: "piranshahr", nameFa: "پیرانشهر", nameEn: "Piranshahr" },
          { code: "naqadeh", nameFa: "نقده", nameEn: "Naqadeh" },
          { code: "maku", nameFa: "ماکو", nameEn: "Maku" },
          { code: "oshnavieh", nameFa: "اشنویه", nameEn: "Oshnavieh" },
        ],
      },
      {
        code: "ARD",
        nameFa: "اردبیل",
        nameEn: "Ardabil",
        cities: [
          { code: "ardabil", nameFa: "اردبیل", nameEn: "Ardabil" },
          { code: "parsabad", nameFa: "پارس‌آباد", nameEn: "Parsabad" },
          { code: "meshginshahr", nameFa: "مشگین‌شهر", nameEn: "Meshginshahr" },
          { code: "khalkhal", nameFa: "خلخال", nameEn: "Khalkhal" },
          { code: "germi", nameFa: "گرمی", nameEn: "Germi" },
          { code: "bilehsavar", nameFa: "بیله‌سوار", nameEn: "Bileh Savar" },
        ],
      },
      {
        code: "ESF",
        nameFa: "اصفهان",
        nameEn: "Isfahan",
        cities: [
          { code: "isfahan", nameFa: "اصفهان", nameEn: "Isfahan" },
          { code: "kashan", nameFa: "کاشان", nameEn: "Kashan" },
          { code: "khomeinishahr", nameFa: "خمینی‌شهر", nameEn: "Khomeyni Shahr" },
          { code: "najafabad", nameFa: "نجف‌آباد", nameEn: "Najafabad" },
          { code: "shahinshahr", nameFa: "شاهین‌شهر", nameEn: "Shahinshahr" },
          { code: "shahrreza", nameFa: "شهرضا", nameEn: "Shahreza" },
          { code: "fooladshahr", nameFa: "فولادشهر", nameEn: "Fooladshahr" },
          { code: "zarinshahr", nameFa: "زرین‌شهر", nameEn: "Zarrinshahr" },
          { code: "naein", nameFa: "نائین", nameEn: "Naein" },
          { code: "golpayegan", nameFa: "گلپایگان", nameEn: "Golpayegan" },
          { code: "khansar", nameFa: "خوانسار", nameEn: "Khansar" },
          { code: "ardekan-esf", nameFa: "اردستان", nameEn: "Ardestan" },
          { code: "natanz", nameFa: "نطنز", nameEn: "Natanz" },
        ],
      },
      {
        code: "ALB",
        nameFa: "البرز",
        nameEn: "Alborz",
        cities: [
          { code: "karaj", nameFa: "کرج", nameEn: "Karaj" },
          { code: "fardis", nameFa: "فردیس", nameEn: "Fardis" },
          { code: "nazarabad", nameFa: "نظرآباد", nameEn: "Nazarabad" },
          { code: "hashtgerd", nameFa: "هشتگرد", nameEn: "Hashtgerd" },
          { code: "mohammadshahr", nameFa: "محمدشهر", nameEn: "Mohammadshahr" },
          { code: "kamalshahr", nameFa: "کمال‌شهر", nameEn: "Kamalshahr" },
          { code: "mahdashat", nameFa: "ماهدشت", nameEn: "Mahdasht" },
        ],
      },
      {
        code: "ILM",
        nameFa: "ایلام",
        nameEn: "Ilam",
        cities: [
          { code: "ilam", nameFa: "ایلام", nameEn: "Ilam" },
          { code: "dehloran", nameFa: "دهلران", nameEn: "Dehloran" },
          { code: "mehran", nameFa: "مهران", nameEn: "Mehran" },
          { code: "abdanan", nameFa: "آبدانان", nameEn: "Abdanan" },
          { code: "eyvan", nameFa: "ایوان", nameEn: "Eyvan" },
        ],
      },
      {
        code: "BSH",
        nameFa: "بوشهر",
        nameEn: "Bushehr",
        cities: [
          { code: "bushehr", nameFa: "بوشهر", nameEn: "Bushehr" },
          { code: "borazjan", nameFa: "برازجان", nameEn: "Borazjan" },
          { code: "ganaveh", nameFa: "گناوه", nameEn: "Ganaveh" },
          { code: "kangan", nameFa: "کنگان", nameEn: "Kangan" },
          { code: "asaluyeh", nameFa: "عسلویه", nameEn: "Asaluyeh" },
          { code: "deylam", nameFa: "دیلم", nameEn: "Deylam" },
          { code: "jam", nameFa: "جم", nameEn: "Jam" },
        ],
      },
      {
        code: "TEH",
        nameFa: "تهران",
        nameEn: "Tehran",
        cities: [
          { code: "tehran", nameFa: "تهران", nameEn: "Tehran" },
          { code: "eslamshahr", nameFa: "اسلامشهر", nameEn: "Eslamshahr" },
          { code: "shahriar", nameFa: "شهریار", nameEn: "Shahriar" },
          { code: "qods", nameFa: "قدس", nameEn: "Qods" },
          { code: "malard", nameFa: "ملارد", nameEn: "Malard" },
          { code: "pakdasht", nameFa: "پاکدشت", nameEn: "Pakdasht" },
          { code: "varamin", nameFa: "ورامین", nameEn: "Varamin" },
          { code: "rey", nameFa: "ری", nameEn: "Rey" },
          { code: "qarchak", nameFa: "قرچک", nameEn: "Qarchak" },
          { code: "pardis", nameFa: "پردیس", nameEn: "Pardis" },
          { code: "damavand", nameFa: "دماوند", nameEn: "Damavand" },
          { code: "firuzkuh", nameFa: "فیروزکوه", nameEn: "Firuzkuh" },
          { code: "robatkarim", nameFa: "رباط‌کریم", nameEn: "Robat Karim" },
          { code: "baharstan", nameFa: "بهارستان", nameEn: "Baharestan" },
          { code: "parand", nameFa: "پرند", nameEn: "Parand" },
        ],
      },
      {
        code: "CHB",
        nameFa: "چهارمحال و بختیاری",
        nameEn: "Chaharmahal and Bakhtiari",
        cities: [
          { code: "shahrekord", nameFa: "شهرکرد", nameEn: "Shahrekord" },
          { code: "borujen", nameFa: "بروجن", nameEn: "Borujen" },
          { code: "farsan", nameFa: "فارسان", nameEn: "Farsan" },
          { code: "lordegan", nameFa: "لردگان", nameEn: "Lordegan" },
          { code: "saman", nameFa: "سامان", nameEn: "Saman" },
        ],
      },
      {
        code: "SKH",
        nameFa: "خراسان جنوبی",
        nameEn: "South Khorasan",
        cities: [
          { code: "birjand", nameFa: "بیرجند", nameEn: "Birjand" },
          { code: "qaen", nameFa: "قائن", nameEn: "Qaen" },
          { code: "ferdows", nameFa: "فردوس", nameEn: "Ferdows" },
          { code: "tabas", nameFa: "طبس", nameEn: "Tabas" },
          { code: "nehbandan", nameFa: "نهبندان", nameEn: "Nehbandan" },
          { code: "sarayan", nameFa: "سرایان", nameEn: "Sarayan" },
        ],
      },
      {
        code: "RKH",
        nameFa: "خراسان رضوی",
        nameEn: "Razavi Khorasan",
        cities: [
          { code: "mashhad", nameFa: "مشهد", nameEn: "Mashhad" },
          { code: "neyshabur", nameFa: "نیشابور", nameEn: "Neyshabur" },
          { code: "sabzevar", nameFa: "سبزوار", nameEn: "Sabzevar" },
          { code: "torbat-heydarieh", nameFa: "تربت حیدریه", nameEn: "Torbat-e Heydarieh" },
          { code: "kashmar", nameFa: "کاشمر", nameEn: "Kashmar" },
          { code: "quchan", nameFa: "قوچان", nameEn: "Quchan" },
          { code: "torbat-jam", nameFa: "تربت جام", nameEn: "Torbat-e Jam" },
          { code: "chenaran", nameFa: "چناران", nameEn: "Chenaran" },
          { code: "gonabad", nameFa: "گناباد", nameEn: "Gonabad" },
          { code: "taybad", nameFa: "تایباد", nameEn: "Taybad" },
          { code: "dargaz", nameFa: "درگز", nameEn: "Dargaz" },
          { code: "khaf", nameFa: "خواف", nameEn: "Khaf" },
          { code: "fariman", nameFa: "فریمان", nameEn: "Fariman" },
          { code: "sarakhs", nameFa: "سرخس", nameEn: "Sarakhs" },
        ],
      },
      {
        code: "NKH",
        nameFa: "خراسان شمالی",
        nameEn: "North Khorasan",
        cities: [
          { code: "bojnord", nameFa: "بجنورد", nameEn: "Bojnord" },
          { code: "shirvan", nameFa: "شیروان", nameEn: "Shirvan" },
          { code: "esfarayen", nameFa: "اسفراین", nameEn: "Esfarayen" },
          { code: "ashkhaneh", nameFa: "آشخانه", nameEn: "Ashkhaneh" },
          { code: "faruj", nameFa: "فاروج", nameEn: "Faruj" },
        ],
      },
      {
        code: "KHZ",
        nameFa: "خوزستان",
        nameEn: "Khuzestan",
        cities: [
          { code: "ahvaz", nameFa: "اهواز", nameEn: "Ahvaz" },
          { code: "abadan", nameFa: "آبادان", nameEn: "Abadan" },
          { code: "khorramshahr", nameFa: "خرمشهر", nameEn: "Khorramshahr" },
          { code: "dezful", nameFa: "دزفول", nameEn: "Dezful" },
          { code: "andimeshk", nameFa: "اندیمشک", nameEn: "Andimeshk" },
          { code: "mahshahr", nameFa: "بندر ماهشهر", nameEn: "Bandar-e Mahshahr" },
          { code: "shushtar", nameFa: "شوشتر", nameEn: "Shushtar" },
          { code: "izeh", nameFa: "ایذه", nameEn: "Izeh" },
          { code: "behbahan", nameFa: "بهبهان", nameEn: "Behbahan" },
          { code: "shadegan", nameFa: "شادگان", nameEn: "Shadegan" },
          { code: "ramhormoz", nameFa: "رامهرمز", nameEn: "Ramhormoz" },
          { code: "shush", nameFa: "شوش", nameEn: "Shush" },
          { code: "omidiyeh", nameFa: "امیدیه", nameEn: "Omidiyeh" },
        ],
      },
      {
        code: "ZJN",
        nameFa: "زنجان",
        nameEn: "Zanjan",
        cities: [
          { code: "zanjan", nameFa: "زنجان", nameEn: "Zanjan" },
          { code: "abhar", nameFa: "ابهر", nameEn: "Abhar" },
          { code: "khorramdarreh", nameFa: "خرمدره", nameEn: "Khorramdarreh" },
          { code: "qeydar", nameFa: "قیدار", nameEn: "Qeydar" },
          { code: "hidaj", nameFa: "هیدج", nameEn: "Hidaj" },
        ],
      },
      {
        code: "SMN",
        nameFa: "سمنان",
        nameEn: "Semnan",
        cities: [
          { code: "semnan", nameFa: "سمنان", nameEn: "Semnan" },
          { code: "shahroud", nameFa: "شاهرود", nameEn: "Shahrud" },
          { code: "damghan", nameFa: "دامغان", nameEn: "Damghan" },
          { code: "garmsar", nameFa: "گرمسار", nameEn: "Garmsar" },
          { code: "mahdishahr", nameFa: "مهدی‌شهر", nameEn: "Mahdishahr" },
        ],
      },
      {
        code: "SBA",
        nameFa: "سیستان و بلوچستان",
        nameEn: "Sistan and Baluchestan",
        cities: [
          { code: "zahedan", nameFa: "زاهدان", nameEn: "Zahedan" },
          { code: "zabol", nameFa: "زابل", nameEn: "Zabol" },
          { code: "iranshahr", nameFa: "ایرانشهر", nameEn: "Iranshahr" },
          { code: "chabahar", nameFa: "چابهار", nameEn: "Chabahar" },
          { code: "khash", nameFa: "خاش", nameEn: "Khash" },
          { code: "saravan", nameFa: "سراوان", nameEn: "Saravan" },
          { code: "konarak", nameFa: "کنارک", nameEn: "Konarak" },
          { code: "nikshahr", nameFa: "نیک‌شهر", nameEn: "Nikshahr" },
        ],
      },
      {
        code: "FRS",
        nameFa: "فارس",
        nameEn: "Fars",
        cities: [
          { code: "shiraz", nameFa: "شیراز", nameEn: "Shiraz" },
          { code: "marvdasht", nameFa: "مرودشت", nameEn: "Marvdasht" },
          { code: "jahrom", nameFa: "جهرم", nameEn: "Jahrom" },
          { code: "kazerun", nameFa: "کازرون", nameEn: "Kazerun" },
          { code: "fasa", nameFa: "فسا", nameEn: "Fasa" },
          { code: "lar", nameFa: "لار", nameEn: "Lar" },
          { code: "darab", nameFa: "داراب", nameEn: "Darab" },
          { code: "firuzabad", nameFa: "فیروزآباد", nameEn: "Firuzabad" },
          { code: "abadeh", nameFa: "آباده", nameEn: "Abadeh" },
          { code: "neyriz", nameFa: "نی‌ریز", nameEn: "Neyriz" },
        ],
      },
      {
        code: "QZV",
        nameFa: "قزوین",
        nameEn: "Qazvin",
        cities: [
          { code: "qazvin", nameFa: "قزوین", nameEn: "Qazvin" },
          { code: "takestan", nameFa: "تاکستان", nameEn: "Takestan" },
          { code: "abyek", nameFa: "آبیک", nameEn: "Abyek" },
          { code: "alvand", nameFa: "الوند", nameEn: "Alvand" },
          { code: "mohammadiyeh", nameFa: "محمدیه", nameEn: "Mohammadiyeh" },
        ],
      },
      {
        code: "QOM",
        nameFa: "قم",
        nameEn: "Qom",
        cities: [
          { code: "qom", nameFa: "قم", nameEn: "Qom" },
          { code: "qanavat", nameFa: "قنوات", nameEn: "Qanavat" },
        ],
      },
      {
        code: "KRD",
        nameFa: "کردستان",
        nameEn: "Kurdistan",
        cities: [
          { code: "sanandaj", nameFa: "سنندج", nameEn: "Sanandaj" },
          { code: "saqqez", nameFa: "سقز", nameEn: "Saqqez" },
          { code: "marivan", nameFa: "مریوان", nameEn: "Marivan" },
          { code: "baneh", nameFa: "بانه", nameEn: "Baneh" },
          { code: "qorveh", nameFa: "قروه", nameEn: "Qorveh" },
          { code: "bijar", nameFa: "بیجار", nameEn: "Bijar" },
          { code: "kamyaran", nameFa: "کامیاران", nameEn: "Kamyaran" },
          { code: "divandareh", nameFa: "دیواندره", nameEn: "Divandareh" },
        ],
      },
      {
        code: "KRM",
        nameFa: "کرمان",
        nameEn: "Kerman",
        cities: [
          { code: "kerman", nameFa: "کرمان", nameEn: "Kerman" },
          { code: "sirjan", nameFa: "سیرجان", nameEn: "Sirjan" },
          { code: "rafsanjan", nameFa: "رفسنجان", nameEn: "Rafsanjan" },
          { code: "jiroft", nameFa: "جیرفت", nameEn: "Jiroft" },
          { code: "bam", nameFa: "بم", nameEn: "Bam" },
          { code: "zarand", nameFa: "زرند", nameEn: "Zarand" },
          { code: "kahnuj", nameFa: "کهنوج", nameEn: "Kahnuj" },
          { code: "shahrbabak", nameFa: "شهربابک", nameEn: "Shahr-e Babak" },
        ],
      },
      {
        code: "KSH",
        nameFa: "کرمانشاه",
        nameEn: "Kermanshah",
        cities: [
          { code: "kermanshah", nameFa: "کرمانشاه", nameEn: "Kermanshah" },
          { code: "eslamabad-gharb", nameFa: "اسلام‌آباد غرب", nameEn: "Eslamabad-e Gharb" },
          { code: "sonqor", nameFa: "سنقر", nameEn: "Sonqor" },
          { code: "harsin", nameFa: "هرسین", nameEn: "Harsin" },
          { code: "kangavar", nameFa: "کنگاور", nameEn: "Kangavar" },
          { code: "javanrud", nameFa: "جوانرود", nameEn: "Javanrud" },
          { code: "paveh", nameFa: "پاوه", nameEn: "Paveh" },
          { code: "sarpolzahab", nameFa: "سرپل ذهاب", nameEn: "Sarpol-e Zahab" },
        ],
      },
      {
        code: "KBA",
        nameFa: "کهگیلویه و بویراحمد",
        nameEn: "Kohgiluyeh and Boyer-Ahmad",
        cities: [
          { code: "yasuj", nameFa: "یاسوج", nameEn: "Yasuj" },
          { code: "dogonbadan", nameFa: "دوگنبدان", nameEn: "Dogonbadan" },
          { code: "dehdasht", nameFa: "دهدشت", nameEn: "Dehdasht" },
        ],
      },
      {
        code: "GLS",
        nameFa: "گلستان",
        nameEn: "Golestan",
        cities: [
          { code: "gorgan", nameFa: "گرگان", nameEn: "Gorgan" },
          { code: "gonbad", nameFa: "گنبد کاووس", nameEn: "Gonbad-e Kavus" },
          { code: "bandar-torkaman", nameFa: "بندر ترکمن", nameEn: "Bandar Torkaman" },
          { code: "aliabad", nameFa: "علی‌آباد کتول", nameEn: "Aliabad-e Katul" },
          { code: "azadshahr", nameFa: "آزادشهر", nameEn: "Azadshahr" },
          { code: "kordkuy", nameFa: "کردکوی", nameEn: "Kordkuy" },
          { code: "kalaleh", nameFa: "کلاله", nameEn: "Kalaleh" },
          { code: "minudasht", nameFa: "مینودشت", nameEn: "Minudasht" },
        ],
      },
      {
        code: "GIL",
        nameFa: "گیلان",
        nameEn: "Gilan",
        cities: [
          { code: "rasht", nameFa: "رشت", nameEn: "Rasht" },
          { code: "anzali", nameFa: "بندر انزلی", nameEn: "Bandar-e Anzali" },
          { code: "lahijan", nameFa: "لاهیجان", nameEn: "Lahijan" },
          { code: "langarud", nameFa: "لنگرود", nameEn: "Langarud" },
          { code: "astara", nameFa: "آستارا", nameEn: "Astara" },
          { code: "rudsar", nameFa: "رودسر", nameEn: "Rudsar" },
          { code: "taleshan", nameFa: "تالش", nameEn: "Talesh" },
          { code: "somehsara", nameFa: "صومعه‌سرا", nameEn: "Someh Sara" },
          { code: "fuman", nameFa: "فومن", nameEn: "Fuman" },
          { code: "astaneh", nameFa: "آستانه اشرفیه", nameEn: "Astaneh-ye Ashrafiyeh" },
        ],
      },
      {
        code: "LOR",
        nameFa: "لرستان",
        nameEn: "Lorestan",
        cities: [
          { code: "khorramabad", nameFa: "خرم‌آباد", nameEn: "Khorramabad" },
          { code: "borujerd", nameFa: "بروجرد", nameEn: "Borujerd" },
          { code: "dorud", nameFa: "دورود", nameEn: "Dorud" },
          { code: "aligudarz", nameFa: "الیگودرز", nameEn: "Aligudarz" },
          { code: "kuhdasht", nameFa: "کوهدشت", nameEn: "Kuhdasht" },
          { code: "aleshtar", nameFa: "الشتر", nameEn: "Aleshtar" },
          { code: "nurabad", nameFa: "نورآباد", nameEn: "Nurabad" },
          { code: "azna", nameFa: "ازنا", nameEn: "Azna" },
        ],
      },
      {
        code: "MZN",
        nameFa: "مازندران",
        nameEn: "Mazandaran",
        cities: [
          { code: "sari", nameFa: "ساری", nameEn: "Sari" },
          { code: "babol", nameFa: "بابل", nameEn: "Babol" },
          { code: "amol", nameFa: "آمل", nameEn: "Amol" },
          { code: "qaemshahr", nameFa: "قائمشهر", nameEn: "Qaem Shahr" },
          { code: "babolsar", nameFa: "بابلسر", nameEn: "Babolsar" },
          { code: "tonekabon", nameFa: "تنکابن", nameEn: "Tonekabon" },
          { code: "chalus", nameFa: "چالوس", nameEn: "Chalus" },
          { code: "nowshahr", nameFa: "نوشهر", nameEn: "Nowshahr" },
          { code: "behshahr", nameFa: "بهشهر", nameEn: "Behshahr" },
          { code: "neka", nameFa: "نکا", nameEn: "Neka" },
          { code: "ramsar", nameFa: "رامسر", nameEn: "Ramsar" },
          { code: "fereydunkenar", nameFa: "فریدونکنار", nameEn: "Fereydunkenar" },
        ],
      },
      {
        code: "MKZ",
        nameFa: "مرکزی",
        nameEn: "Markazi",
        cities: [
          { code: "arak", nameFa: "اراک", nameEn: "Arak" },
          { code: "saveh", nameFa: "ساوه", nameEn: "Saveh" },
          { code: "khomeyn", nameFa: "خمین", nameEn: "Khomeyn" },
          { code: "mahallat", nameFa: "محلات", nameEn: "Mahallat" },
          { code: "delijan", nameFa: "دلیجان", nameEn: "Delijan" },
          { code: "tafresh", nameFa: "تفرش", nameEn: "Tafresh" },
          { code: "shazand", nameFa: "شازند", nameEn: "Shazand" },
        ],
      },
      {
        code: "HRZ",
        nameFa: "هرمزگان",
        nameEn: "Hormozgan",
        cities: [
          { code: "bandarabbas", nameFa: "بندرعباس", nameEn: "Bandar Abbas" },
          { code: "minab", nameFa: "میناب", nameEn: "Minab" },
          { code: "qeshm", nameFa: "قشم", nameEn: "Qeshm" },
          { code: "bandarlengeh", nameFa: "بندر لنگه", nameEn: "Bandar Lengeh" },
          { code: "kish", nameFa: "کیش", nameEn: "Kish" },
          { code: "hajiabad", nameFa: "حاجی‌آباد", nameEn: "Hajiabad" },
          { code: "rudan", nameFa: "رودان", nameEn: "Rudan" },
        ],
      },
      {
        code: "HMD",
        nameFa: "همدان",
        nameEn: "Hamadan",
        cities: [
          { code: "hamadan", nameFa: "همدان", nameEn: "Hamadan" },
          { code: "malayer", nameFa: "ملایر", nameEn: "Malayer" },
          { code: "nahavand", nameFa: "نهاوند", nameEn: "Nahavand" },
          { code: "tuyserkan", nameFa: "تویسرکان", nameEn: "Tuyserkan" },
          { code: "asadabad", nameFa: "اسدآباد", nameEn: "Asadabad" },
          { code: "kabudarahang", nameFa: "کبودرآهنگ", nameEn: "Kabudarahang" },
        ],
      },
      {
        code: "YZD",
        nameFa: "یزد",
        nameEn: "Yazd",
        cities: [
          { code: "yazd", nameFa: "یزد", nameEn: "Yazd" },
          { code: "meybod", nameFa: "میبد", nameEn: "Meybod" },
          { code: "ardakan", nameFa: "اردکان", nameEn: "Ardakan" },
          { code: "bafq", nameFa: "بافق", nameEn: "Bafq" },
          { code: "mehriz", nameFa: "مهریز", nameEn: "Mehriz" },
          { code: "taft", nameFa: "تفت", nameEn: "Taft" },
          { code: "abarkuh", nameFa: "ابرکوه", nameEn: "Abarkuh" },
        ],
      },
    ],
  },
  {
    iso2: "IQ",
    iso3: "IRQ",
    phoneCode: "+964",
    nameFa: "عراق",
    nameEn: "Iraq",
    sortOrder: 2,
    provinces: [
      {
        code: "BG",
        nameFa: "بغداد",
        nameEn: "Baghdad",
        cities: [
          { code: "baghdad", nameFa: "بغداد", nameEn: "Baghdad" },
          { code: "kadhimiya", nameFa: "کاظمین", nameEn: "Kadhimiya" },
          { code: "sadr-city", nameFa: "صدر", nameEn: "Sadr City" },
        ],
      },
      {
        code: "KA",
        nameFa: "کربلا",
        nameEn: "Karbala",
        cities: [{ code: "karbala", nameFa: "کربلا", nameEn: "Karbala" }],
      },
      {
        code: "NA",
        nameFa: "نجف",
        nameEn: "Najaf",
        cities: [
          { code: "najaf", nameFa: "نجف", nameEn: "Najaf" },
          { code: "kufa", nameFa: "کوفه", nameEn: "Kufa" },
        ],
      },
      {
        code: "BA",
        nameFa: "بصره",
        nameEn: "Basra",
        cities: [
          { code: "basra", nameFa: "بصره", nameEn: "Basra" },
          { code: "umm-qasr", nameFa: "ام‌قصر", nameEn: "Umm Qasr" },
        ],
      },
      {
        code: "NI",
        nameFa: "نینوا",
        nameEn: "Nineveh",
        cities: [{ code: "mosul", nameFa: "موصل", nameEn: "Mosul" }],
      },
      {
        code: "AR",
        nameFa: "اربیل",
        nameEn: "Erbil",
        cities: [{ code: "erbil", nameFa: "اربیل", nameEn: "Erbil" }],
      },
      {
        code: "SU",
        nameFa: "سلیمانیه",
        nameEn: "Sulaymaniyah",
        cities: [{ code: "sulaymaniyah", nameFa: "سلیمانیه", nameEn: "Sulaymaniyah" }],
      },
      {
        code: "DA",
        nameFa: "دهوک",
        nameEn: "Dohuk",
        cities: [{ code: "dohuk", nameFa: "دهوک", nameEn: "Dohuk" }],
      },
      {
        code: "BB",
        nameFa: "بابل",
        nameEn: "Babylon",
        cities: [{ code: "hillah", nameFa: "حله", nameEn: "Hillah" }],
      },
      {
        code: "DI",
        nameFa: "دیاله",
        nameEn: "Diyala",
        cities: [{ code: "baqubah", nameFa: "بعقوبه", nameEn: "Baqubah" }],
      },
      {
        code: "AN",
        nameFa: "انبار",
        nameEn: "Al Anbar",
        cities: [
          { code: "ramadi", nameFa: "رمادی", nameEn: "Ramadi" },
          { code: "fallujah", nameFa: "فلوجه", nameEn: "Fallujah" },
        ],
      },
      {
        code: "SD",
        nameFa: "صلاح‌الدین",
        nameEn: "Saladin",
        cities: [
          { code: "tikrit", nameFa: "تکریت", nameEn: "Tikrit" },
          { code: "samarra", nameFa: "سامرا", nameEn: "Samarra" },
        ],
      },
      {
        code: "WA",
        nameFa: "واسط",
        nameEn: "Wasit",
        cities: [{ code: "kut", nameFa: "کوت", nameEn: "Kut" }],
      },
      {
        code: "MA",
        nameFa: "میسان",
        nameEn: "Maysan",
        cities: [{ code: "amarah", nameFa: "عماره", nameEn: "Amarah" }],
      },
      {
        code: "DQ",
        nameFa: "ذی‌قار",
        nameEn: "Dhi Qar",
        cities: [{ code: "nasiriyah", nameFa: "ناصریه", nameEn: "Nasiriyah" }],
      },
      {
        code: "MU",
        nameFa: "مثنی",
        nameEn: "Muthanna",
        cities: [{ code: "samawah", nameFa: "سماوه", nameEn: "Samawah" }],
      },
      {
        code: "QA",
        nameFa: "قادسیه",
        nameEn: "Al-Qadisiyyah",
        cities: [{ code: "diwaniyah", nameFa: "دیوانیه", nameEn: "Diwaniyah" }],
      },
      {
        code: "KI",
        nameFa: "کرکوک",
        nameEn: "Kirkuk",
        cities: [{ code: "kirkuk", nameFa: "کرکوک", nameEn: "Kirkuk" }],
      },
    ],
  },
  {
    iso2: "PK",
    iso3: "PAK",
    phoneCode: "+92",
    nameFa: "پاکستان",
    nameEn: "Pakistan",
    sortOrder: 3,
    provinces: [
      {
        code: "IS",
        nameFa: "اسلام‌آباد",
        nameEn: "Islamabad Capital Territory",
        cities: [{ code: "islamabad", nameFa: "اسلام‌آباد", nameEn: "Islamabad" }],
      },
      {
        code: "PB",
        nameFa: "پنجاب",
        nameEn: "Punjab",
        cities: [
          { code: "lahore", nameFa: "لاهور", nameEn: "Lahore" },
          { code: "faisalabad", nameFa: "فیصل‌آباد", nameEn: "Faisalabad" },
          { code: "rawalpindi", nameFa: "راولپندی", nameEn: "Rawalpindi" },
          { code: "multan", nameFa: "ملتان", nameEn: "Multan" },
          { code: "gujranwala", nameFa: "گوجرانواله", nameEn: "Gujranwala" },
          { code: "sialkot", nameFa: "سیالکوت", nameEn: "Sialkot" },
        ],
      },
      {
        code: "SD",
        nameFa: "سند",
        nameEn: "Sindh",
        cities: [
          { code: "karachi", nameFa: "کراچی", nameEn: "Karachi" },
          { code: "hyderabad", nameFa: "حیدرآباد", nameEn: "Hyderabad" },
          { code: "sukkur", nameFa: "سکور", nameEn: "Sukkur" },
        ],
      },
      {
        code: "KP",
        nameFa: "خیبر پختونخوا",
        nameEn: "Khyber Pakhtunkhwa",
        cities: [
          { code: "peshawar", nameFa: "پیشاور", nameEn: "Peshawar" },
          { code: "mardan", nameFa: "مردان", nameEn: "Mardan" },
          { code: "abbottabad", nameFa: "ابوت‌آباد", nameEn: "Abbottabad" },
        ],
      },
      {
        code: "BA",
        nameFa: "بلوچستان",
        nameEn: "Balochistan",
        cities: [
          { code: "quetta", nameFa: "کویته", nameEn: "Quetta" },
          { code: "gwadar", nameFa: "گوادر", nameEn: "Gwadar" },
        ],
      },
      {
        code: "GB",
        nameFa: "گلگت-بلتستان",
        nameEn: "Gilgit-Baltistan",
        cities: [
          { code: "gilgit", nameFa: "گلگت", nameEn: "Gilgit" },
          { code: "skardu", nameFa: "اسکاردو", nameEn: "Skardu" },
        ],
      },
      {
        code: "JK",
        nameFa: "آزاد کشمیر",
        nameEn: "Azad Kashmir",
        cities: [
          { code: "muzaffarabad", nameFa: "مظفرآباد", nameEn: "Muzaffarabad" },
          { code: "mirpur", nameFa: "میرپور", nameEn: "Mirpur" },
        ],
      },
    ],
  },
  {
    iso2: "AF",
    iso3: "AFG",
    phoneCode: "+93",
    nameFa: "افغانستان",
    nameEn: "Afghanistan",
    sortOrder: 4,
    provinces: [
      {
        code: "KAB",
        nameFa: "کابل",
        nameEn: "Kabul",
        cities: [{ code: "kabul", nameFa: "کابل", nameEn: "Kabul" }],
      },
      {
        code: "HER",
        nameFa: "هرات",
        nameEn: "Herat",
        cities: [{ code: "herat", nameFa: "هرات", nameEn: "Herat" }],
      },
      {
        code: "KAN",
        nameFa: "قندهار",
        nameEn: "Kandahar",
        cities: [{ code: "kandahar", nameFa: "قندهار", nameEn: "Kandahar" }],
      },
      {
        code: "BAL",
        nameFa: "بلخ",
        nameEn: "Balkh",
        cities: [{ code: "mazar", nameFa: "مزار شریف", nameEn: "Mazar-i-Sharif" }],
      },
      {
        code: "NAN",
        nameFa: "ننگرهار",
        nameEn: "Nangarhar",
        cities: [{ code: "jalalabad", nameFa: "جلال‌آباد", nameEn: "Jalalabad" }],
      },
      {
        code: "BAM",
        nameFa: "بامیان",
        nameEn: "Bamyan",
        cities: [{ code: "bamyan", nameFa: "بامیان", nameEn: "Bamyan" }],
      },
      {
        code: "GHA",
        nameFa: "غزنی",
        nameEn: "Ghazni",
        cities: [{ code: "ghazni", nameFa: "غزنی", nameEn: "Ghazni" }],
      },
      {
        code: "KDZ",
        nameFa: "قندوز",
        nameEn: "Kunduz",
        cities: [{ code: "kunduz", nameFa: "قندوز", nameEn: "Kunduz" }],
      },
      {
        code: "HEL",
        nameFa: "هلمند",
        nameEn: "Helmand",
        cities: [{ code: "lashkargah", nameFa: "لشکرگاه", nameEn: "Lashkar Gah" }],
      },
      {
        code: "PIA",
        nameFa: "پکتیا",
        nameEn: "Paktia",
        cities: [{ code: "gardez", nameFa: "گردیز", nameEn: "Gardez" }],
      },
    ],
  },
  {
    iso2: "IN",
    iso3: "IND",
    phoneCode: "+91",
    nameFa: "هند",
    nameEn: "India",
    sortOrder: 5,
    provinces: [
      {
        code: "DL",
        nameFa: "دهلی",
        nameEn: "Delhi",
        cities: [
          { code: "new-delhi", nameFa: "دهلی نو", nameEn: "New Delhi" },
          { code: "delhi", nameFa: "دهلی", nameEn: "Delhi" },
        ],
      },
      {
        code: "MH",
        nameFa: "مهاراشترا",
        nameEn: "Maharashtra",
        cities: [
          { code: "mumbai", nameFa: "بمبئی", nameEn: "Mumbai" },
          { code: "pune", nameFa: "پونه", nameEn: "Pune" },
          { code: "nagpur", nameFa: "ناگپور", nameEn: "Nagpur" },
        ],
      },
      {
        code: "UP",
        nameFa: "اوتار پرادش",
        nameEn: "Uttar Pradesh",
        cities: [
          { code: "lucknow", nameFa: "لکهنو", nameEn: "Lucknow" },
          { code: "varanasi", nameFa: "واراناسی", nameEn: "Varanasi" },
          { code: "agra", nameFa: "آگرا", nameEn: "Agra" },
          { code: "kanpur", nameFa: "کانپور", nameEn: "Kanpur" },
        ],
      },
      {
        code: "RJ",
        nameFa: "راجستان",
        nameEn: "Rajasthan",
        cities: [
          { code: "jaipur", nameFa: "جیپور", nameEn: "Jaipur" },
          { code: "udaipur", nameFa: "اودایپور", nameEn: "Udaipur" },
          { code: "jodhpur", nameFa: "جودپور", nameEn: "Jodhpur" },
        ],
      },
      {
        code: "WB",
        nameFa: "بنگال غربی",
        nameEn: "West Bengal",
        cities: [{ code: "kolkata", nameFa: "کلکته", nameEn: "Kolkata" }],
      },
      {
        code: "TN",
        nameFa: "تامیل نادو",
        nameEn: "Tamil Nadu",
        cities: [{ code: "chennai", nameFa: "چنای", nameEn: "Chennai" }],
      },
      {
        code: "KA",
        nameFa: "کارناتاکا",
        nameEn: "Karnataka",
        cities: [
          { code: "bengaluru", nameFa: "بنگلور", nameEn: "Bengaluru" },
          { code: "mysuru", nameFa: "میسور", nameEn: "Mysuru" },
        ],
      },
      {
        code: "GJ",
        nameFa: "گجرات",
        nameEn: "Gujarat",
        cities: [
          { code: "ahmedabad", nameFa: "احمدآباد", nameEn: "Ahmedabad" },
          { code: "surat", nameFa: "سورات", nameEn: "Surat" },
        ],
      },
      {
        code: "PB",
        nameFa: "پنجاب",
        nameEn: "Punjab",
        cities: [
          { code: "amritsar", nameFa: "امرتسر", nameEn: "Amritsar" },
          { code: "ludhiana", nameFa: "لودهیانا", nameEn: "Ludhiana" },
        ],
      },
      {
        code: "KL",
        nameFa: "کرالا",
        nameEn: "Kerala",
        cities: [
          { code: "thiruvananthapuram", nameFa: "تریواندروم", nameEn: "Thiruvananthapuram" },
          { code: "kochi", nameFa: "کوچی", nameEn: "Kochi" },
        ],
      },
      {
        code: "TG",
        nameFa: "تلانگانا",
        nameEn: "Telangana",
        cities: [{ code: "hyderabad", nameFa: "حیدرآباد", nameEn: "Hyderabad" }],
      },
      {
        code: "BR",
        nameFa: "بهار",
        nameEn: "Bihar",
        cities: [{ code: "patna", nameFa: "پتنا", nameEn: "Patna" }],
      },
      {
        code: "JK",
        nameFa: "جامو و کشمیر",
        nameEn: "Jammu and Kashmir",
        cities: [
          { code: "srinagar", nameFa: "سرینگر", nameEn: "Srinagar" },
          { code: "jammu", nameFa: "جامو", nameEn: "Jammu" },
        ],
      },
    ],
  },
];
